print(' /      \\')
print('/        \\')
print('\        /')
print(' \______/')
print('\        /')
print(' \______/')
print('+--------+')
print(' /      \\')
print('/        \\')
print('|  STOP  |')
print('\        /')
print(' \______/')
print(' /      \\')
print('/        \\')
print('+--------+')
